In [3]:
import pandas as pd 
import re

In [4]:
data = pd.read_csv(f"data\edos_labelled_aggregated.csv")
data

,rewire_id,text,label_sexist,label_category,label_vector,split
0,sexism2022_english-9609,"In Nigeria, if you rape a woman, the men rape ...",not sexist,none,none,dev
1,sexism2022_english-16993,"Then, she's a keeper. üòâ",not sexist,none,none,train
2,sexism2022_english-13149,This is like the Metallica video where the poo...,not sexist,none,none,train
3,sexism2022_english-13021,woman?,not sexist,none,none,train
4,sexism2022_english-966,I bet she wished she had a gun,not sexist,none,none,dev
...,...,...,...,...,...,...
19995,sexism2022_english-5228,girls really get fucked almost every weekend ?,not sexist,none,none,train
19996,sexism2022_english-10140,The hatred for moslems are Reasonable and Just...,not sexist,none,none,train
19997,sexism2022_english-9726,Now this is a woman who gets it. üëÜ,not sexist,none,none,train
19998,sexism2022_english-13365,‚ÄúAmerican Idol‚Äù finalist [USER] said nothing i...,not sexist,none,none,train
19999,sexism2022_english-3523,this bi--th should be stoped she's the rapist,sexist,2. derogation,2.2 aggressive and emotive attacks,test

In [46]:
data = data[["text", "label_category", "split"]]

In [47]:
data.duplicated().sum().item()

0

In [48]:
data['label_category'].value_counts(sort=True, ascending=True)

label_category
1. threats, plans to harm and incitement      443
4. prejudiced discussions                     475
3. animosity                                 1665
2. derogation                                2271
none                                        15146
Name: count, dtype: int64

In [63]:
data.loc[:,'label_type'] = data['label_category'].str.replace(r"^\d+\.\s*", "", regex=True)
data.loc[:,"category_code"] = pd.to_numeric(data["label_category"].str.extract(r"^(\d+)\.")[0], errors='coerce').fillna(4).astype(int)
data

,text,label_category,split,label_type,category_code
0,"In Nigeria, if you rape a woman, the men rape ...",none,dev,none,4
1,"Then, she's a keeper. üòâ",none,train,none,4
2,This is like the Metallica video where the poo...,none,train,none,4
3,woman?,none,train,none,4
4,I bet she wished she had a gun,none,dev,none,4
...,...,...,...,...,...
19995,girls really get fucked almost every weekend ?,none,train,none,4
19996,The hatred for moslems are Reasonable and Just...,none,train,none,4
19997,Now this is a woman who gets it. üëÜ,none,train,none,4
19998,‚ÄúAmerican Idol‚Äù finalist [USER] said nothing i...,none,train,none,4
19999,this bi--th should be stoped she's the rapist,2. derogation,test,derogation,2

In [64]:
splits = {split_name: group for split_name, group in data.groupby('split')}

In [65]:
train_df = splits.get('train')
test_df = splits.get('test')
val_df = splits.get('dev')

In [66]:
train_df.drop(['split'], axis=1, inplace=True)
test_df.drop(['split'], axis=1, inplace=True)
val_df.drop(['split'], axis=1, inplace=True)

In [69]:
val_df

,text,label_category,label_type,category_code
0,"In Nigeria, if you rape a woman, the men rape ...",none,none,4
4,I bet she wished she had a gun,none,none,4
9,I agree with that but at the same time I know ...,2. derogation,derogation,2
15,democrats from Minnesota (leftist muzzie shith...,2. derogation,derogation,2
29,Texas jury sentences Jordanian immigrant to de...,none,none,4
...,...,...,...,...
19887,The future is female guys,none,none,4
19909,Dude do not ever text a girl something like th...,none,none,4
19915,I cum really hard from anal & clitoral stimula...,none,none,4
19967,Oooh that hurt kind like that Jewish girl who ...,none,none,4
19974,This. Let go of anger. Of cognitive dissonance...,none,none,4

In [ ]:
# data['target_category'] = data['label_category'].astype('category')
# data['target_category'] = data['target_category'].cat.codes
# data

In [74]:
train_df.to_csv('train.csv', index=False)
val_df.to_csv('val.csv', index=False)
test_df.to_csv('test.csv', index=False)

In [70]:
print("train_df row count:", train_df['label_category'].count())
print(train_df['label_category'].value_counts(sort=True, ascending=True))

train_df row count: 14000
label_category
1. threats, plans to harm and incitement      310
4. prejudiced discussions                     333
3. animosity                                 1165
2. derogation                                1590
none                                        10602
Name: count, dtype: int64

In [71]:
print("val_df row count:", val_df['label_category'].count())
print(val_df['label_category'].value_counts(sort=True, ascending=True))

val_df row count: 2000
label_category
1. threats, plans to harm and incitement      44
4. prejudiced discussions                     48
3. animosity                                 167
2. derogation                                227
none                                        1514
Name: count, dtype: int64

In [72]:
print("test_df row count:", test_df['label_category'].count())
print(test_df['label_category'].value_counts(sort=True, ascending=True))

test_df row count: 4000
label_category
1. threats, plans to harm and incitement      89
4. prejudiced discussions                     94
3. animosity                                 333
2. derogation                                454
none                                        3030
Name: count, dtype: int64